/****************************************************
 HEADLINE MAKER

 vars.js

 WORD DATABASE + GAME VARIABLES
****************************************************/



/****************************************************
 WORD BANKS
****************************************************/
var newspapers = [

    "THE DAILY HEADLINE",
    "THE MORNING GAZETTE",
    "THE BOSTON GLOBE",
    "THE TIMES",
    "THE HERALD",
    "THE DAILY CHRONICLE",
    "THE EVENING STANDARD",
    "THE CITY POST",
    "THE NATIONAL NEWS",
    "THE WORLD REPORTER",
    "THE DAILY SENTINEL",
    "THE METRO EXPRESS"

];

/****************************************************
 VOCABULARY PACKS
****************************************************/

var vocabulary = {

general:{

people:[

"Teacher",
"Doctor",
"Student",
"Police Officer",
"Chef",
"Footballer",
"Singer",
"Actor",
"Farmer",
"Scientist",
"Pilot",
"Firefighter",
"Builder",
"Nurse",
"Tourist",
"Artist",
"Judge",
"Journalist",
"Astronaut",
"Business Owner",
"Driver",
"Engineer",
"Musician",
"Writer",
"Photographer",
"Dancer",
"Painter",
"Mechanic",
"Lawyer",
"Dentist",
"Veterinarian",
"Professor",
"Coach",
"Bank Worker",
"Shop Owner",
"Security Guard",
"Electrician",
"Gardener",
"Architect",
"Designer",
"Student Leader",
"Researcher",
"Explorer",
"Inventor",
"Surgeon",
"Paramedic",
"Reporter",
"Manager",
"Volunteer",
"Neighbour"

],


actions:[

"finds",
"loses",
"rescues",
"builds",
"wins",
"breaks",
"discovers",
"buys",
"creates",
"opens",
"closes",
"meets",
"visits",
"catches",
"delivers",
"protects",
"reports",
"investigates",
"announces",
"celebrates",
"helps",
"changes",
"repairs",
"designs",
"creates",
"discovers",
"organises",
"prepares",
"shares",
"collects",
"moves",
"starts",
"finishes",
"improves",
"solves",
"finds",
"chooses",
"learns",
"teaches",
"explains",
"controls",
"discovers",
"checks",
"returns",
"opens",
"closes",
"joins",
"creates",
"builds",
"protects"

],


objects:[

"a hidden treasure",
"a missing phone",
"a new invention",
"a valuable painting",
"a lost suitcase",
"a strange object",
"a secret message",
"a championship trophy",
"a rare animal",
"a mysterious box",
"a new restaurant",
"a stolen bicycle",
"a famous book",
"a surprise gift",
"a special machine",
"a family photo",
"a large diamond",
"a new computer",
"an old map",
"a valuable document",
"a forgotten letter",
"a golden key",
"a broken watch",
"a new car",
"a school project",
"a music instrument",
"a sports award",
"a camera",
"a robot",
"a new building",
"a collection of books",
"a secret room",
"a rare flower",
"a beautiful painting",
"a travel bag",
"a computer program",
"a medical report",
"a science experiment",
"a birthday cake",
"a phone message",
"a lost wallet",
"a special ticket",
"a handmade gift",
"a magic trick",
"a new recipe",
"a shopping list",
"a strange package",
"a football",
"a family letter",
"a treasure map"

],


places:[

"in London",
"in Paris",
"at school",
"at the airport",
"on a train",
"in a museum",
"at the beach",
"in a forest",
"in a supermarket",
"at the zoo",
"in a castle",
"in New York",
"at the hospital",
"in a restaurant",
"at the stadium",
"in a library",
"on a mountain",
"at home",
"in the city",
"near the river",
"at the park",
"in a village",
"at the station",
"in a shopping centre",
"inside a hotel",
"on a farm",
"at the university",
"in a factory",
"at the office",
"on a bridge",
"near the ocean",
"in a garden",
"at a concert",
"in a theatre",
"at a school event",
"on a street",
"in a market",
"at a playground",
"inside a shop",
"near a lake",
"in the countryside",
"at a festival",
"in a sports centre",
"at a café",
"on an island",
"near a waterfall",
"in a neighbourhood",
"at a train station",
"in a small town",
"at a community centre"

]

},



advanced:{

people:[

"Economist",
"Diplomat",
"Archaeologist",
"Entrepreneur",
"Philanthropist",
"Researcher",
"Conservationist",
"Architect",
"Engineer",
"Psychologist",
"Historian",
"Photographer",
"Mathematician",
"Pharmacist",
"Negotiator",
"Explorer",
"Inventor",
"Politician",
"Ambassador",
"Scientist",
"Professor",
"Environmentalist",
"Journalist",
"Analyst",
"Consultant",
"Strategist",
"Designer",
"Developer",
"Surgeon",
"Investigator",
"Law Specialist",
"Financial Expert",
"Medical Researcher",
"University Leader",
"Technology Expert",
"Climate Scientist",
"Business Director",
"Project Manager",
"Community Leader",
"Human Rights Activist",
"Energy Specialist",
"Urban Planner",
"Security Expert",
"Education Specialist",
"Market Researcher",
"Legal Advisor",
"Policy Maker",
"Trade Representative",
"International Officer",
"Innovation Leader"

],


actions:[

"negotiates",
"investigates",
"constructs",
"transforms",
"discovers",
"evaluates",
"proposes",
"implements",
"demonstrates",
"publishes",
"introduces",
"examines",
"supports",
"develops",
"analyses",
"prevents",
"predicts",
"expands",
"coordinates",
"organises",
"creates",
"launches",
"improves",
"establishes",
"researches",
"designs",
"reviews",
"explores",
"invests",
"announces",
"recommends",
"challenges",
"reveals",
"produces",
"investigates",
"solves",
"manages",
"discovers",
"changes",
"rebuilds",
"protects",
"controls",
"measures",
"compares",
"identifies",
"creates",
"develops",
"explains",
"introduces",
"updates"

],


objects:[

"a renewable energy project",
"an ancient manuscript",
"a scientific breakthrough",
"a digital currency",
"a medical treatment",
"an archaeological site",
"a conservation plan",
"a historical document",
"a business proposal",
"a research paper",
"a transport system",
"a communication network",
"a climate report",
"a cultural festival",
"an education programme",
"a security system",
"a robotics project",
"a financial report",
"a wildlife reserve",
"an engineering design",
"a new technology",
"a global agreement",
"a medical discovery",
"a space programme",
"a scientific device",
"an environmental study",
"a new invention",
"a government report",
"a business strategy",
"a digital platform",
"a research centre",
"a construction project",
"a new policy",
"a transport network",
"a renewable resource",
"a safety system",
"a technology solution",
"a health programme",
"an international plan",
"a training programme",
"a new material",
"a scientific model",
"a cultural project",
"a public service",
"a communication tool",
"a financial system",
"an economic report",
"a development project",
"a research database",
"an advanced machine"

],


places:[

"in Antarctica",
"at the United Nations",
"in Silicon Valley",
"at a research centre",
"in the Sahara Desert",
"in the Pacific Ocean",
"at an international conference",
"in a remote village",
"inside a volcano",
"on the International Space Station",
"in the Himalayas",
"in a nature reserve",
"in a government office",
"at a technology expo",
"in a rainforest",
"in Geneva",
"at an archaeological dig",
"in a financial district",
"at a science museum",
"in a national laboratory",
"in a university campus",
"at a global summit",
"in a modern city",
"at a research institute",
"in a developing country",
"at a medical centre",
"in a technology hub",
"at a conference hall",
"in a coastal region",
"in a desert area",
"at a space centre",
"in an industrial zone",
"inside a laboratory",
"at an international airport",
"in a historic district",
"at a cultural centre",
"in a major city",
"near a border region",
"at a government building",
"in an economic centre",
"at a science conference",
"in a conservation area",
"at a training facility",
"in a remote location",
"at a public institution",
"in a research village",
"at an innovation centre",
"in a financial market",
"at an education centre"

]

},

travel:{

people:[

"Tourist",
"Traveller",
"Pilot",
"Flight Attendant",
"Hotel Manager",
"Tour Guide",
"Driver",
"Photographer",
"Explorer",
"Backpacker",
"Chef",
"Student",
"Family",
"Business Traveller",
"Journalist",
"Travel Agent",
"Passenger",
"Ship Captain",
"Engineer",
"Adventure Guide",
"Mountain Climber",
"Translator",
"Local Resident",
"Tour Operator",
"Bus Driver",
"Train Driver",
"Airport Worker",
"Hotel Guest",
"Travel Blogger",
"Historian",
"Archaeologist",
"Researcher",
"Festival Visitor",
"Wildlife Expert",
"Island Guide",
"Park Ranger",
"Restaurant Owner",
"Language Student",
"Culture Expert",
"Map Maker",
"Road Traveller",
"Boat Captain",
"Adventure Photographer",
"Holiday Planner",
"Flight Manager",
"Tour Leader",
"Travel Writer",
"Explorer Team",
"Visitor",
"Backpacking Student"

],


actions:[

"visits",
"discovers",
"explores",
"travels to",
"misses",
"loses",
"finds",
"books",
"cancels",
"photographs",
"rescues",
"opens",
"closes",
"arrives",
"leaves",
"crosses",
"flies over",
"reviews",
"reports",
"celebrates",
"climbs",
"follows",
"travels through",
"maps",
"guides",
"searches for",
"discovers",
"investigates",
"records",
"shares",
"learns",
"experiences",
"prepares",
"organises",
"plans",
"explores",
"visits",
"returns",
"changes",
"survives",
"finds",
"travels across",
"photographs",
"documents",
"creates",
"discovers",
"enjoys",
"protects",
"observes",
"celebrates"

],


objects:[

"a lost suitcase",
"a passport",
"a plane ticket",
"a travel guide",
"a camera",
"a hotel key",
"a mysterious map",
"a famous painting",
"a souvenir",
"a rare object",
"a luxury car",
"a stolen bag",
"a boat",
"a train ticket",
"a hidden island",
"a travel diary",
"a special gift",
"a foreign language book",
"a valuable necklace",
"a strange package",
"a camping tent",
"a mountain map",
"a hotel reservation",
"a flight schedule",
"a local recipe",
"a traditional costume",
"a museum ticket",
"a travel backpack",
"a boat engine",
"a historic photograph",
"a guide book",
"a rare souvenir",
"a hiking tool",
"a safety device",
"a travel document",
"a city map",
"a cultural object",
"a festival ticket",
"a camera drone",
"a holiday plan",
"a restaurant menu",
"a train map",
"a bicycle",
"a navigation system",
"a rescue kit",
"a passport photo",
"a tourist card",
"a language dictionary",
"a travel magazine",
"a camping guide"

],


places:[

"at the airport",
"in Paris",
"in London",
"at a hotel",
"on a tropical island",
"in the mountains",
"at a train station",
"on a cruise ship",
"in a foreign country",
"at the beach",
"in a national park",
"in the desert",
"in a small village",
"at a famous museum",
"in a busy city",
"near a volcano",
"at a historic castle",
"in the countryside",
"on a remote island",
"at a tourist attraction",
"in a rainforest",
"near a waterfall",
"at a famous landmark",
"in a coastal town",
"at a railway station",
"in a mountain village",
"inside a cave",
"on a desert road",
"at a cultural festival",
"in an ancient city",
"near a river",
"at a nature reserve",
"in a shopping district",
"at a local market",
"on a safari park",
"in a national monument",
"at a city centre",
"on a famous bridge",
"in a small island village",
"at a travel centre",
"in a historic town",
"near a glacier",
"at a theme park",
"on a countryside road",
"in a foreign city",
"at a seaside resort",
"inside a famous building",
"at a harbour",
"near a lake",
"on a scenic route"

]

},

business:{

people:[

"Business Owner",
"Manager",
"CEO",
"Employee",
"Entrepreneur",
"Investor",
"Customer",
"Sales Manager",
"Company Director",
"Marketing Expert",
"Accountant",
"Financial Adviser",
"Shop Owner",
"Factory Worker",
"Office Manager",
"Project Leader",
"Business Consultant",
"Bank Manager",
"Designer",
"Engineer",
"Product Manager",
"Team Leader",
"Company Founder",
"Trade Representative",
"Researcher",
"Economist",
"Supervisor",
"Recruiter",
"Customer Service Worker",
"Software Developer",
"Business Analyst",
"Operations Manager",
"Advertising Expert",
"Retail Manager",
"Warehouse Worker",
"Import Manager",
"Export Manager",
"Lawyer",
"Contract Manager",
"Training Manager",
"Investment Expert",
"Market Researcher",
"Brand Manager",
"Company Lawyer",
"Financial Expert",
"Business Reporter",
"Startup Founder",
"Office Worker",
"Technology Manager",
"Production Manager"

],


actions:[

"launches",
"creates",
"develops",
"invests",
"expands",
"opens",
"closes",
"buys",
"sells",
"produces",
"designs",
"improves",
"announces",
"changes",
"manages",
"organises",
"builds",
"creates",
"introduces",
"plans",
"grows",
"reduces",
"increases",
"controls",
"negotiates",
"signs",
"changes",
"reviews",
"tests",
"markets",
"advertises",
"exports",
"imports",
"replaces",
"updates",
"creates",
"discovers",
"partners with",
"supports",
"develops",
"changes",
"investigates",
"reports",
"solves",
"prepares",
"opens",
"improves",
"transforms",
"delivers",
"provides"

],


objects:[

"a new product",
"a business plan",
"a company building",
"a financial report",
"a new service",
"a marketing campaign",
"a business contract",
"a new machine",
"a digital platform",
"a company website",
"a new invention",
"a customer database",
"a training programme",
"a delivery system",
"a computer system",
"a company logo",
"a new advertisement",
"a financial agreement",
"a research project",
"a production line",
"a factory",
"a new restaurant",
"a shopping centre",
"a technology product",
"a mobile application",
"a company vehicle",
"a new brand",
"a business strategy",
"a sales report",
"a company policy",
"a new store",
"a workplace system",
"an investment plan",
"a customer service programme",
"a new office",
"a business report",
"a financial system",
"a product design",
"a company magazine",
"a market study",
"a payment system",
"a company database",
"a new website",
"a business model",
"a training course",
"a trade agreement",
"a company project",
"a new service package",
"a workplace improvement plan",
"a customer survey"

],


places:[

"in an office",
"in a company building",
"at a factory",
"in a shopping centre",
"at a business meeting",
"in a financial district",
"at a trade conference",
"in a technology park",
"at a bank",
"in a small business",
"at an international market",
"in a city centre",
"at a company headquarters",
"in a warehouse",
"at a business centre",
"in a factory area",
"at a conference hall",
"in a retail store",
"at an online marketplace",
"in a local community",
"at a training centre",
"in an industrial area",
"at a university",
"in a research centre",
"at an international office",
"in a modern building",
"at a company event",
"in a commercial area",
"at a business park",
"in a global market",
"at a startup office",
"in a shopping district",
"at an investment centre",
"in a production area",
"at an export centre",
"in a financial market",
"at a company meeting",
"in a workplace",
"at a sales event",
"in a customer centre",
"at a technology conference",
"in a business school",
"at a company factory",
"in a commercial district",
"at a business exhibition",
"in a corporate office",
"at a networking event",
"in a city market",
"at an international company",
"in a professional centre"

]

},

crime:{

people:[

"Police Officer",
"Detective",
"Investigator",
"Judge",
"Lawyer",
"Reporter",
"Witness",
"Security Guard",
"Police Chief",
"Inspector",
"Crime Expert",
"Journalist",
"Neighbour",
"Business Owner",
"Bank Worker",
"Computer Specialist",
"Government Official",
"Legal Adviser",
"Officer",
"Researcher",
"Private Detective",
"Prosecutor",
"Defence Lawyer",
"Community Leader",
"Shop Owner",
"Driver",
"Customer",
"Scientist",
"Photographer",
"Security Manager",
"Building Manager",
"Local Resident",
"Court Worker",
"Evidence Expert",
"Police Recruit",
"Border Officer",
"Customs Officer",
"Translator",
"Technology Expert",
"Insurance Worker",
"Bank Manager",
"Property Owner",
"Investigator Team",
"News Reporter",
"Legal Specialist",
"Government Inspector",
"Safety Officer",
"Neighbourhood Leader",
"Community Worker",
"Emergency Worker",
"Case Manager"

],


actions:[

"investigates",
"discovers",
"finds",
"reports",
"questions",
"arrests",
"searches",
"examines",
"checks",
"follows",
"solves",
"reveals",
"identifies",
"protects",
"investigates",
"prevents",
"tracks",
"reviews",
"collects",
"records",
"announces",
"explains",
"discovers",
"reports",
"checks",
"interviews",
"studies",
"examines",
"uncovers",
"investigates",
"prepares",
"tests",
"confirms",
"solves",
"investigates",
"searches for",
"finds",
"analyses",
"questions",
"reviews",
"protects",
"monitors",
"controls",
"investigates",
"reports",
"discovers",
"examines",
"identifies",
"prepares",
"prevents"

],


objects:[

"a missing phone",
"a stolen bicycle",
"a secret document",
"a mysterious package",
"a lost wallet",
"a hidden message",
"a security camera",
"a valuable painting",
"a computer file",
"a stolen vehicle",
"a missing item",
"a suspicious letter",
"a strange object",
"a bank record",
"a photograph",
"a key",
"a document",
"a report",
"a map",
"a piece of evidence",
"a forgotten bag",
"a damaged machine",
"a broken lock",
"a security system",
"a digital record",
"a personal file",
"a company document",
"a lost passport",
"a valuable item",
"a hidden camera",
"a phone message",
"a financial record",
"a contract",
"a missing computer",
"a vehicle report",
"a customer record",
"a secret code",
"a stolen package",
"a damaged building",
"a safety report",
"a legal document",
"a court file",
"a research note",
"a witness statement",
"a business record",
"a travel document",
"a lost object",
"a warning message",
"a security report",
"a case file"

],


places:[

"at a police station",
"in a city centre",
"at a bank",
"in a shopping centre",
"at an airport",
"in a neighbourhood",
"at a company office",
"in a courtroom",
"at a train station",
"in a hotel",
"at a museum",
"in a local shop",
"at a university",
"in a government building",
"at a warehouse",
"in a factory",
"at a border crossing",
"in a residential area",
"at a public park",
"in a business district",
"at a school",
"in a library",
"at a restaurant",
"in a car park",
"at a security centre",
"in a city building",
"at a transport station",
"in a small town",
"at a community centre",
"in a financial district",
"at a technology centre",
"in a shopping area",
"at a company headquarters",
"in a local market",
"at a hotel entrance",
"near a river",
"at a railway station",
"in a village",
"at a government office",
"in an apartment building",
"at a sports centre",
"inside a vehicle",
"at a public event",
"in a parking area",
"at a research centre",
"near a school",
"inside a business",
"at a court building",
"in a residential street",
"at a security office"

]

},

technology:{

people:[

"Engineer",
"Programmer",
"Scientist",
"Researcher",
"Software Developer",
"Technology Expert",
"Inventor",
"Designer",
"Robot Engineer",
"Computer Specialist",
"Data Analyst",
"Artificial Intelligence Expert",
"Cybersecurity Officer",
"Business Owner",
"Student",
"Professor",
"Machine Operator",
"Website Designer",
"App Developer",
"Technology Manager",
"Laboratory Worker",
"Digital Creator",
"Computer Teacher",
"Game Developer",
"Electronics Engineer",
"Science Reporter",
"Research Director",
"Product Designer",
"Innovation Leader",
"Database Manager",
"Network Specialist",
"Systems Engineer",
"Robotics Expert",
"Medical Researcher",
"Space Scientist",
"Environmental Scientist",
"Technology Journalist",
"Startup Founder",
"Digital Consultant",
"Online Creator",
"Communication Specialist",
"Automation Expert",
"Data Scientist",
"Security Specialist",
"Virtual Reality Designer",
"Hardware Engineer",
"Mobile Developer",
"Technology Student",
"Future Planner",
"Science Teacher"

],


actions:[

"creates",
"develops",
"designs",
"builds",
"improves",
"tests",
"launches",
"updates",
"discovers",
"creates",
"programs",
"repairs",
"controls",
"develops",
"investigates",
"analyses",
"connects",
"changes",
"introduces",
"explains",
"creates",
"produces",
"develops",
"improves",
"solves",
"updates",
"protects",
"discovers",
"creates",
"designs",
"tests",
"reviews",
"builds",
"changes",
"manages",
"organises",
"programs",
"operates",
"researches",
"announces",
"reveals",
"examines",
"improves",
"creates",
"develops",
"prepares",
"controls",
"explores",
"predicts",
"transforms"

],


objects:[

"a robot",
"a computer program",
"a mobile application",
"a new device",
"an artificial intelligence system",
"a digital assistant",
"a smart phone",
"a computer system",
"a security program",
"a website",
"a video game",
"a virtual reality machine",
"a communication tool",
"a data system",
"a technology platform",
"a space device",
"a medical machine",
"a smart camera",
"a digital map",
"a computer network",
"a learning system",
"a smart vehicle",
"a scientific machine",
"a new battery",
"a robot assistant",
"a software update",
"a research project",
"a technology product",
"a digital service",
"a computer chip",
"a satellite system",
"a communication network",
"a new invention",
"a health device",
"a testing machine",
"a science project",
"a computer database",
"a security system",
"a smart home system",
"a digital payment system",
"a robot vehicle",
"a language app",
"a learning platform",
"a technology solution",
"a machine system",
"a data program",
"a computer model",
"a future invention",
"a science tool",
"a digital camera"

],


places:[

"in a laboratory",
"at a technology centre",
"in Silicon Valley",
"at a university",
"in a research centre",
"inside a factory",
"at a science museum",
"in a computer company",
"at a technology conference",
"in a modern city",
"at a space centre",
"in an engineering building",
"at a startup office",
"in a digital laboratory",
"at an innovation centre",
"in a science park",
"at a business conference",
"in a classroom",
"at a research institute",
"in a technology park",
"inside a computer lab",
"at a medical centre",
"in a development centre",
"at an international exhibition",
"in a company office",
"at a robotics centre",
"in a university laboratory",
"at a science conference",
"inside a factory building",
"at an online event",
"in a technology market",
"at a design studio",
"in a communication centre",
"at a training centre",
"in a software company",
"at an electronics factory",
"in a research building",
"at a digital centre",
"in a modern workplace",
"at an engineering centre",
"in a science facility",
"at a technology show",
"in a computer classroom",
"at a global conference",
"in a development laboratory",
"at an innovation event",
"in a technology company",
"at a research station",
"in a future city",
"inside a digital centre"

]

}

};

/****************************************************
 LOAD VOCABULARY PACK
****************************************************/

function loadVocabulary(level){

    if(!vocabulary[level]){

        console.error(
            "Vocabulary pack not found:",
            level
        );

        level = "general";

    }


    people = vocabulary[level].people.slice();

    actions = vocabulary[level].actions.slice();

    objects = vocabulary[level].objects.slice();

    places = vocabulary[level].places.slice();

}

/****************************************************
CURRENT VOCABULARY
****************************************************/

var people = [];
var actions = [];
var objects = [];
var places = [];

loadVocabulary("general");


/****************************************************
 GAME VARIABLES
****************************************************/


var numPlayers = 0;



var scores = {};



var currentEditor = 0;



var currentReporter = 0;



var playerHeadlines = {};



var currentHeadline = {

    person:null,

    action:null,

    object:null,

    place:null

};




var currentChoices = {};
